import { InMemoryDatabase } from 'brackets-memory-db';
import { BracketsManager } from 'brackets-manager';
import { BracketsViewer } from './main';
import { convertStageStructureToViewerData } from './dto/converter';
import type { Config, ViewerData, BracketDimensions } from './types';

const viewer = new BracketsViewer();
const baseRender = viewer.render.bind(viewer);
let containerIdCounter = 0;

/**
 * Renders a bracket inside a specific container element.
 *
 * @param container The HTMLElement (or selector) where the bracket should be rendered.
 * @param data The data generated by brackets-manager.
 * @param config Optional configuration overrides.
 * @returns The natural dimensions of the rendered bracket, or null.
 */
export async function renderBracket(container: HTMLElement | string, data: ViewerData, config: Partial<Config> = {}): Promise<BracketDimensions | null> {
    const resolvedContainer = typeof container === 'string'
        ? document.querySelector(container)
        : container;

    if (!resolvedContainer)
        throw new Error('Container element not found');

    if (!(resolvedContainer instanceof HTMLElement))
        throw new Error('Container element must be an HTMLElement');

    const resolvedConfig: Partial<Config> = { ...config };

    if (!resolvedConfig.selector) {
        if (!resolvedContainer.id)
            resolvedContainer.id = `bv-container-${++containerIdCounter}`;

        resolvedConfig.selector = `#${resolvedContainer.id}`;
    }

    if (resolvedConfig.clear === undefined)
        resolvedConfig.clear = true;

    await baseRender(data, resolvedConfig);
    return viewer.getBracketDimensions();
}

// SSR guard — window assignments only in browser environments
if (typeof window !== 'undefined') {
    window.bracketsViewer = viewer;
    window.bracketsViewer.render = async (data: ViewerData, cfg?: Partial<Config>): Promise<void> => {
        await renderBracket('.brackets-viewer', data, cfg ?? {});
    };
    window.bracketsViewerDTO = {
        convertStageStructureToViewerData,
    };
    window.inMemoryDatabase = new InMemoryDatabase();
    window.bracketsManager = new BracketsManager(window.inMemoryDatabase);
}

export { BracketsViewer };
export * from './types';
export * from './dto';

// Headless layout API (SSR-safe, no DOM dependencies)
export { computeBracketLayout } from './computeBracketLayout';
export type { BracketLayoutResult, BracketMatchNode, ResolvedOpponent } from './layout/BracketLayoutResult';
export type { RoundHeader, ConnectorLine, MatchPosition, SwissPanelPosition, Point, ConnectorType } from './layout/types';
export type { LayoutConfig } from './viewModels';
