import { InMemoryDatabase } from 'brackets-memory-db';
import { BracketsManager } from 'brackets-manager';
import { BracketsViewer } from './main';
import type { Config, ViewerData } from './types';

const viewer = new BracketsViewer();
const baseRender = viewer.render.bind(viewer);
let containerIdCounter = 0;

/**
 * Renders a bracket inside a specific container element.
 *
 * @param container The HTMLElement (or selector) where the bracket should be rendered.
 * @param data The data generated by brackets-manager.
 * @param config Optional configuration overrides.
 */
export function renderBracket(container: HTMLElement | string, data: ViewerData, config: Partial<Config> = {}): Promise<void> {
    const resolvedContainer = typeof container === 'string'
        ? document.querySelector(container)
        : container;

    if (!resolvedContainer)
        throw new Error('Container element not found');

    if (!(resolvedContainer instanceof HTMLElement))
        throw new Error('Container element must be an HTMLElement');

    const resolvedConfig: Partial<Config> = { ...config };

    if (!resolvedConfig.selector) {
        if (!resolvedContainer.id)
            resolvedContainer.id = `bv-container-${++containerIdCounter}`;

        resolvedConfig.selector = `#${resolvedContainer.id}`;
    }

    if (resolvedConfig.clear === undefined)
        resolvedConfig.clear = true;

    return baseRender(data, resolvedConfig);
}

window.bracketsViewer = viewer;
window.bracketsViewer.render = (data, cfg) => renderBracket('.brackets-viewer', data, cfg ?? {});
window.inMemoryDatabase = new InMemoryDatabase();
window.bracketsManager = new BracketsManager(window.inMemoryDatabase);

export { BracketsViewer };
export * from './types';
