/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an advancement link between two matches
 * @export
 * @interface BracketEdgeResponse
 */
export interface BracketEdgeResponse {
    /**
     * Source match identifier
     * @type {string}
     * @memberof BracketEdgeResponse
     */
    fromMatchId?: string;
    /**
     * Placement rank in the source match that advances
     * @type {number}
     * @memberof BracketEdgeResponse
     */
    fromRank?: number;
    /**
     * Destination match identifier
     * @type {string}
     * @memberof BracketEdgeResponse
     */
    toMatchId?: string;
    /**
     * Destination slot number
     * @type {number}
     * @memberof BracketEdgeResponse
     */
    toSlot?: number;
}

/**
 * Check if a given object implements the BracketEdgeResponse interface.
 */
export function instanceOfBracketEdgeResponse(value: object): value is BracketEdgeResponse {
    return true;
}

export function BracketEdgeResponseFromJSON(json: any): BracketEdgeResponse {
    return BracketEdgeResponseFromJSONTyped(json, false);
}

export function BracketEdgeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketEdgeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fromMatchId': json['fromMatchId'] == null ? undefined : json['fromMatchId'],
        'fromRank': json['fromRank'] == null ? undefined : json['fromRank'],
        'toMatchId': json['toMatchId'] == null ? undefined : json['toMatchId'],
        'toSlot': json['toSlot'] == null ? undefined : json['toSlot'],
    };
}

export function BracketEdgeResponseToJSON(json: any): BracketEdgeResponse {
    return BracketEdgeResponseToJSONTyped(json, false);
}

export function BracketEdgeResponseToJSONTyped(value?: BracketEdgeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromMatchId': value['fromMatchId'],
        'fromRank': value['fromRank'],
        'toMatchId': value['toMatchId'],
        'toSlot': value['toSlot'],
    };
}

