/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
import type { MatchSlotResponse } from './MatchSlotResponse';
import {
    MatchSlotResponseFromJSON,
    MatchSlotResponseFromJSONTyped,
    MatchSlotResponseToJSON,
    MatchSlotResponseToJSONTyped,
} from './MatchSlotResponse';

/**
 * Full match data for bracket rendering
 * @export
 * @interface MatchStructureResponse
 */
export interface MatchStructureResponse {
    /**
     * Match identifier
     * @type {string}
     * @memberof MatchStructureResponse
     */
    id?: string;
    /**
     * Bracket ordering index
     * @type {number}
     * @memberof MatchStructureResponse
     */
    matchIndex?: number;
    /**
     * Match lifecycle status
     * @type {string}
     * @memberof MatchStructureResponse
     */
    status?: MatchStructureResponseStatusEnum;
    /**
     * Scheduled start time in ISO-8601
     * @type {Date}
     * @memberof MatchStructureResponse
     */
    scheduledTime?: Date;
    /**
     * True when a final result exists
     * @type {boolean}
     * @memberof MatchStructureResponse
     */
    completed?: boolean;
    /**
     * Participants/slots for this match
     * @type {Array<MatchSlotResponse>}
     * @memberof MatchStructureResponse
     */
    slots?: Array<MatchSlotResponse>;
}


/**
 * @export
 */
export const MatchStructureResponseStatusEnum = {
    Unscheduled: 'UNSCHEDULED',
    Scheduled: 'SCHEDULED',
    Live: 'LIVE',
    Completed: 'COMPLETED'
} as const;
export type MatchStructureResponseStatusEnum = typeof MatchStructureResponseStatusEnum[keyof typeof MatchStructureResponseStatusEnum];


/**
 * Check if a given object implements the MatchStructureResponse interface.
 */
export function instanceOfMatchStructureResponse(value: object): value is MatchStructureResponse {
    return true;
}

export function MatchStructureResponseFromJSON(json: any): MatchStructureResponse {
    return MatchStructureResponseFromJSONTyped(json, false);
}

export function MatchStructureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchStructureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'matchIndex': json['matchIndex'] == null ? undefined : json['matchIndex'],
        'status': json['status'] == null ? undefined : json['status'],
        'scheduledTime': json['scheduledTime'] == null ? undefined : (new Date(json['scheduledTime'])),
        'completed': json['completed'] == null ? undefined : json['completed'],
        'slots': json['slots'] == null ? undefined : ((json['slots'] as Array<any>).map(MatchSlotResponseFromJSON)),
    };
}

export function MatchStructureResponseToJSON(json: any): MatchStructureResponse {
    return MatchStructureResponseToJSONTyped(json, false);
}

export function MatchStructureResponseToJSONTyped(value?: MatchStructureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'matchIndex': value['matchIndex'],
        'status': value['status'],
        'scheduledTime': value['scheduledTime'] == null ? value['scheduledTime'] : value['scheduledTime'].toISOString(),
        'completed': value['completed'],
        'slots': value['slots'] == null ? undefined : ((value['slots'] as Array<any>).map(MatchSlotResponseToJSON)),
    };
}

