/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
/**
 * Participant slot within a match
 * @export
 * @interface MatchSlotResponse
 */
export interface MatchSlotResponse {
    /**
     * Slot number (1-based)
     * @type {number}
     * @memberof MatchSlotResponse
     */
    slot?: number;
    /**
     * Display label for the team or qualifier
     * @type {string}
     * @memberof MatchSlotResponse
     */
    teamName?: string;
    /**
     * Games/rounds won in this match
     * @type {number}
     * @memberof MatchSlotResponse
     */
    gamesWon?: number;
    /**
     * True if this slot is the recorded winner
     * @type {boolean}
     * @memberof MatchSlotResponse
     */
    winner?: boolean;
    /**
     * Source stage name when fed from a prior stage
     * @type {string}
     * @memberof MatchSlotResponse
     */
    sourceStageName?: string;
    /**
     * Source group index when applicable
     * @type {number}
     * @memberof MatchSlotResponse
     */
    sourceGroupIndex?: number;
    /**
     * Placement within the source stage
     * @type {number}
     * @memberof MatchSlotResponse
     */
    sourceRank?: number;
    /**
     * Stage item identifier that feeds this slot
     * @type {string}
     * @memberof MatchSlotResponse
     */
    sourceStageItemId?: string;
}

/**
 * Check if a given object implements the MatchSlotResponse interface.
 */
export function instanceOfMatchSlotResponse(value: object): value is MatchSlotResponse {
    return true;
}

export function MatchSlotResponseFromJSON(json: any): MatchSlotResponse {
    return MatchSlotResponseFromJSONTyped(json, false);
}

export function MatchSlotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchSlotResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'slot': json['slot'] == null ? undefined : json['slot'],
        'teamName': json['teamName'] == null ? undefined : json['teamName'],
        'gamesWon': json['gamesWon'] == null ? undefined : json['gamesWon'],
        'winner': json['winner'] == null ? undefined : json['winner'],
        'sourceStageName': json['sourceStageName'] == null ? undefined : json['sourceStageName'],
        'sourceGroupIndex': json['sourceGroupIndex'] == null ? undefined : json['sourceGroupIndex'],
        'sourceRank': json['sourceRank'] == null ? undefined : json['sourceRank'],
        'sourceStageItemId': json['sourceStageItemId'] == null ? undefined : json['sourceStageItemId'],
    };
}

export function MatchSlotResponseToJSON(json: any): MatchSlotResponse {
    return MatchSlotResponseToJSONTyped(json, false);
}

export function MatchSlotResponseToJSONTyped(value?: MatchSlotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slot': value['slot'],
        'teamName': value['teamName'],
        'gamesWon': value['gamesWon'],
        'winner': value['winner'],
        'sourceStageName': value['sourceStageName'],
        'sourceGroupIndex': value['sourceGroupIndex'],
        'sourceRank': value['sourceRank'],
        'sourceStageItemId': value['sourceStageItemId'],
    };
}

