/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
import type { MatchStructureResponse } from './MatchStructureResponse';
import {
    MatchStructureResponseFromJSON,
    MatchStructureResponseFromJSONTyped,
    MatchStructureResponseToJSON,
    MatchStructureResponseToJSONTyped,
} from './MatchStructureResponse';

/**
 * Round view containing ordered matches for rendering.
 * @export
 * @interface RoundStructureResponse
 */
export interface RoundStructureResponse {
    /**
     * Round number
     * @type {number}
     * @memberof RoundStructureResponse
     */
    number?: number;
    /**
     * Bracket subdivision (winners/losers/etc)
     * @type {string}
     * @memberof RoundStructureResponse
     */
    bracketGroup?: string;
    /**
     * Matches scheduled inside this round
     * @type {Array<MatchStructureResponse>}
     * @memberof RoundStructureResponse
     */
    matches?: Array<MatchStructureResponse>;
}

/**
 * Check if a given object implements the RoundStructureResponse interface.
 */
export function instanceOfRoundStructureResponse(value: object): value is RoundStructureResponse {
    return true;
}

export function RoundStructureResponseFromJSON(json: any): RoundStructureResponse {
    return RoundStructureResponseFromJSONTyped(json, false);
}

export function RoundStructureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoundStructureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'bracketGroup': json['bracketGroup'] == null ? undefined : json['bracketGroup'],
        'matches': json['matches'] == null ? undefined : ((json['matches'] as Array<any>).map(MatchStructureResponseFromJSON)),
    };
}

export function RoundStructureResponseToJSON(json: any): RoundStructureResponse {
    return RoundStructureResponseToJSONTyped(json, false);
}

export function RoundStructureResponseToJSONTyped(value?: RoundStructureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'bracketGroup': value['bracketGroup'],
        'matches': value['matches'] == null ? undefined : ((value['matches'] as Array<any>).map(MatchStructureResponseToJSON)),
    };
}

