/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
import type { RoundStructureResponse } from './RoundStructureResponse';
import {
    RoundStructureResponseFromJSON,
    RoundStructureResponseFromJSONTyped,
    RoundStructureResponseToJSON,
    RoundStructureResponseToJSONTyped,
} from './RoundStructureResponse';
import type { BracketEdgeResponse } from './BracketEdgeResponse';
import {
    BracketEdgeResponseFromJSON,
    BracketEdgeResponseFromJSONTyped,
    BracketEdgeResponseToJSON,
    BracketEdgeResponseToJSONTyped,
} from './BracketEdgeResponse';

/**
 * Represents a single bracket/group (stage item) within a stage.
 * @export
 * @interface StageItemStructureResponse
 */
export interface StageItemStructureResponse {
    /**
     * Stage item identifier
     * @type {string}
     * @memberof StageItemStructureResponse
     */
    id?: string;
    /**
     * Group index (1-based) inside the stage
     * @type {number}
     * @memberof StageItemStructureResponse
     */
    groupIndex?: number;
    /**
     * Rounds contained in this stage item
     * @type {Array<RoundStructureResponse>}
     * @memberof StageItemStructureResponse
     */
    rounds?: Array<RoundStructureResponse>;
    /**
     * Edges describing advancement links between matches
     * @type {Array<BracketEdgeResponse>}
     * @memberof StageItemStructureResponse
     */
    edges?: Array<BracketEdgeResponse>;
}

/**
 * Check if a given object implements the StageItemStructureResponse interface.
 */
export function instanceOfStageItemStructureResponse(value: object): value is StageItemStructureResponse {
    return true;
}

export function StageItemStructureResponseFromJSON(json: any): StageItemStructureResponse {
    return StageItemStructureResponseFromJSONTyped(json, false);
}

export function StageItemStructureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageItemStructureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'groupIndex': json['groupIndex'] == null ? undefined : json['groupIndex'],
        'rounds': json['rounds'] == null ? undefined : ((json['rounds'] as Array<any>).map(RoundStructureResponseFromJSON)),
        'edges': json['edges'] == null ? undefined : ((json['edges'] as Array<any>).map(BracketEdgeResponseFromJSON)),
    };
}

export function StageItemStructureResponseToJSON(json: any): StageItemStructureResponse {
    return StageItemStructureResponseToJSONTyped(json, false);
}

export function StageItemStructureResponseToJSONTyped(value?: StageItemStructureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'groupIndex': value['groupIndex'],
        'rounds': value['rounds'] == null ? undefined : ((value['rounds'] as Array<any>).map(RoundStructureResponseToJSON)),
        'edges': value['edges'] == null ? undefined : ((value['edges'] as Array<any>).map(BracketEdgeResponseToJSON)),
    };
}

