/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
import type { StageItemStructureResponse } from './StageItemStructureResponse';
import {
    StageItemStructureResponseFromJSON,
    StageItemStructureResponseFromJSONTyped,
    StageItemStructureResponseToJSON,
    StageItemStructureResponseToJSONTyped,
} from './StageItemStructureResponse';

/**
 * Complete structural representation for a tournament stage.
 * @export
 * @interface StageStructureResponse
 */
export interface StageStructureResponse {
    /**
     * Stage identifier
     * @type {string}
     * @memberof StageStructureResponse
     */
    stageId?: string;
    /**
     * Stage format
     * @type {string}
     * @memberof StageStructureResponse
     */
    stageType?: StageStructureResponseStageTypeEnum;
    /**
     * Ordered stage items/groups for this stage
     * @type {Array<StageItemStructureResponse>}
     * @memberof StageStructureResponse
     */
    stageItems?: Array<StageItemStructureResponse>;
}


/**
 * @export
 */
export const StageStructureResponseStageTypeEnum = {
    SingleElimination: 'SINGLE_ELIMINATION',
    DoubleElimination: 'DOUBLE_ELIMINATION',
    RoundRobin: 'ROUND_ROBIN',
    Swiss: 'SWISS',
    Ffa: 'FFA'
} as const;
export type StageStructureResponseStageTypeEnum = typeof StageStructureResponseStageTypeEnum[keyof typeof StageStructureResponseStageTypeEnum];


/**
 * Check if a given object implements the StageStructureResponse interface.
 */
export function instanceOfStageStructureResponse(value: object): value is StageStructureResponse {
    return true;
}

export function StageStructureResponseFromJSON(json: any): StageStructureResponse {
    return StageStructureResponseFromJSONTyped(json, false);
}

export function StageStructureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageStructureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'stageId': json['stageId'] == null ? undefined : json['stageId'],
        'stageType': json['stageType'] == null ? undefined : json['stageType'],
        'stageItems': json['stageItems'] == null ? undefined : ((json['stageItems'] as Array<any>).map(StageItemStructureResponseFromJSON)),
    };
}

export function StageStructureResponseToJSON(json: any): StageStructureResponse {
    return StageStructureResponseToJSONTyped(json, false);
}

export function StageStructureResponseToJSONTyped(value?: StageStructureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stageId': value['stageId'],
        'stageType': value['stageType'],
        'stageItems': value['stageItems'] == null ? undefined : ((value['stageItems'] as Array<any>).map(StageItemStructureResponseToJSON)),
    };
}

