/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime';
/**
 * Stage with configuration, structure hints, and live state.
 * @export
 * @interface StageResponse
 */
export interface StageResponse {
    /**
     * Stage identifier.
     * @type {string}
     * @memberof StageResponse
     */
    id?: string;
    /**
     * 1-based ordering of the stage in the tournament.
     * @type {number}
     * @memberof StageResponse
     */
    stageIndex?: number;
    /**
     * Display name for admins.
     * @type {string}
     * @memberof StageResponse
     */
    name?: string;
    /**
     * Stage type.
     * @type {string}
     * @memberof StageResponse
     */
    type?: StageResponseTypeEnum;
    /**
     * Human-friendly type label.
     * @type {string}
     * @memberof StageResponse
     */
    typeName?: string;
    /**
     * Whether a third-place match should be generated.
     * @type {boolean}
     * @memberof StageResponse
     */
    thirdPlaceMatch?: boolean;
    /**
     * Grand final behavior for double elimination.
     * @type {string}
     * @memberof StageResponse
     */
    grandFinalMode?: StageResponseGrandFinalModeEnum;
    /**
     * Bracket size target.
     * @type {number}
     * @memberof StageResponse
     */
    bracketSize?: number;
    /**
     * Number of round-robin groups.
     * @type {number}
     * @memberof StageResponse
     */
    groupCount?: number;
    /**
     * Matches per pair in round robin.
     * @type {number}
     * @memberof StageResponse
     */
    matchesPerPairing?: number;
    /**
     * Swiss rounds count when applicable.
     * @type {number}
     * @memberof StageResponse
     */
    rounds?: number;
    /**
     * Allow draws for round-robin or Swiss.
     * @type {boolean}
     * @memberof StageResponse
     */
    allowDraws?: boolean;
    /**
     * Avoid repeat pairings in Swiss.
     * @type {boolean}
     * @memberof StageResponse
     */
    avoidRematches?: boolean;
    /**
     * Lobby capacity for FFA.
     * @type {number}
     * @memberof StageResponse
     */
    lobbyCapacity?: number;
    /**
     * Number of FFA rounds.
     * @type {number}
     * @memberof StageResponse
     */
    ffaRounds?: number;
    /**
     * Reseed policy label for FFA.
     * @type {string}
     * @memberof StageResponse
     */
    reseedPolicy?: string;
    /**
     * Points earned per kill in FFA.
     * @type {number}
     * @memberof StageResponse
     */
    pointsPerKill?: number;
    /**
     * Placement points mapping for FFA.
     * @type {{ [key: string]: number; }}
     * @memberof StageResponse
     */
    placementPoints?: { [key: string]: number; };
    /**
     * Current lifecycle state for the stage.
     * @type {string}
     * @memberof StageResponse
     */
    state?: StageResponseStateEnum;
}


/**
 * @export
 */
export const StageResponseTypeEnum = {
    SingleElimination: 'SINGLE_ELIMINATION',
    DoubleElimination: 'DOUBLE_ELIMINATION',
    RoundRobin: 'ROUND_ROBIN',
    Swiss: 'SWISS',
    Ffa: 'FFA'
} as const;
export type StageResponseTypeEnum = typeof StageResponseTypeEnum[keyof typeof StageResponseTypeEnum];

/**
 * @export
 */
export const StageResponseGrandFinalModeEnum = {
    OneMatch: 'ONE_MATCH',
    ResetIfFirstLoss: 'RESET_IF_FIRST_LOSS'
} as const;
export type StageResponseGrandFinalModeEnum = typeof StageResponseGrandFinalModeEnum[keyof typeof StageResponseGrandFinalModeEnum];

/**
 * @export
 */
export const StageResponseStateEnum = {
    Draft: 'DRAFT',
    RegOpen: 'REG_OPEN',
    CheckIn: 'CHECK_IN',
    Seeding: 'SEEDING',
    Seeded: 'SEEDED',
    Live: 'LIVE',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type StageResponseStateEnum = typeof StageResponseStateEnum[keyof typeof StageResponseStateEnum];


/**
 * Check if a given object implements the StageResponse interface.
 */
export function instanceOfStageResponse(value: object): value is StageResponse {
    return true;
}

export function StageResponseFromJSON(json: any): StageResponse {
    return StageResponseFromJSONTyped(json, false);
}

export function StageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stageIndex': json['stageIndex'] == null ? undefined : json['stageIndex'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'typeName': json['typeName'] == null ? undefined : json['typeName'],
        'thirdPlaceMatch': json['thirdPlaceMatch'] == null ? undefined : json['thirdPlaceMatch'],
        'grandFinalMode': json['grandFinalMode'] == null ? undefined : json['grandFinalMode'],
        'bracketSize': json['bracketSize'] == null ? undefined : json['bracketSize'],
        'groupCount': json['groupCount'] == null ? undefined : json['groupCount'],
        'matchesPerPairing': json['matchesPerPairing'] == null ? undefined : json['matchesPerPairing'],
        'rounds': json['rounds'] == null ? undefined : json['rounds'],
        'allowDraws': json['allowDraws'] == null ? undefined : json['allowDraws'],
        'avoidRematches': json['avoidRematches'] == null ? undefined : json['avoidRematches'],
        'lobbyCapacity': json['lobbyCapacity'] == null ? undefined : json['lobbyCapacity'],
        'ffaRounds': json['ffaRounds'] == null ? undefined : json['ffaRounds'],
        'reseedPolicy': json['reseedPolicy'] == null ? undefined : json['reseedPolicy'],
        'pointsPerKill': json['pointsPerKill'] == null ? undefined : json['pointsPerKill'],
        'placementPoints': json['placementPoints'] == null ? undefined : json['placementPoints'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function StageResponseToJSON(json: any): StageResponse {
    return StageResponseToJSONTyped(json, false);
}

export function StageResponseToJSONTyped(value?: StageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stageIndex': value['stageIndex'],
        'name': value['name'],
        'type': value['type'],
        'typeName': value['typeName'],
        'thirdPlaceMatch': value['thirdPlaceMatch'],
        'grandFinalMode': value['grandFinalMode'],
        'bracketSize': value['bracketSize'],
        'groupCount': value['groupCount'],
        'matchesPerPairing': value['matchesPerPairing'],
        'rounds': value['rounds'],
        'allowDraws': value['allowDraws'],
        'avoidRematches': value['avoidRematches'],
        'lobbyCapacity': value['lobbyCapacity'],
        'ffaRounds': value['ffaRounds'],
        'reseedPolicy': value['reseedPolicy'],
        'pointsPerKill': value['pointsPerKill'],
        'placementPoints': value['placementPoints'],
        'state': value['state'],
    };
}

